package com.reversecurrent.tennistracker.dal

const val DATABASE_NAME = "tennistrackerdb"
const val PLAYER_TABLE_NAME = "players"
const val PLAYER_TABLE_NAME_COLUMN = "player_name"
const val PLAYER_TABLE_MOBILE_NUMBER_COLUMN = "mobile_number"
const val PLAYER_TABLE_PLAYING_LEVEL_COLUMN = "playing_level"
const val PLAYER_TABLE_PLAYED_BEFORE_COLUMN = "played_before"

const val VENUE_TABLE_NAME = "venues"
const val VENUE_TABLE_NAME_COLUMN = "venue_name"
const val VENUE_TABLE_ALIAS_COLUMN = "venue_alias"
const val VENUE_TABLE_PRIMARY_CONTACT_NUMBER_COLUMN = "primary_contact_number"
const val VENUE_TABLE_PRIMARY_CONTACT_NAME_COLUMN = "primary_contact_name"
const val VENUE_TABLE_ADDRESS_COLUMN = "address"
const val VENUE_TABLE_NUMBER_OF_COURTS_COLUMN = "number_of_courts"
const val VENUE_TABLE_COURT_TYPE_COLUMN = "court_type"
const val VENUE_TABLE_COST_PER_HOUR_COLUMN = "cost_per_hour"
const val VENUE_TABLE_COACHING_AVAILABLE_COLUMN = "coaching_available"

const val SESSION_TABLE_NAME = "sessions"
const val SESSION_TABLE_SESSION_DATE_COLUMN = "session_date"
const val SESSION_TABLE_DURATION_COLUMN = "session_duration"
const val SESSION_TABLE_PLAYING_FORMAT_COLUMN = "session_playing_format"
const val SESSION_TABLE_COST_COLUMN = "session_cost"
const val SESSION_TABLE_NOTES_COLUMN = "session_notes"
const val SESSION_TABLE_PLAYING_STRUCTURE_COLUMN = "session_playing_structure"
const val SESSION_TABLE_REACHED_TIME_COLUMN = "session_reached_time"
const val SESSION_TABLE_WASHED_OUT_COLUMN = "session_washed_out"
const val SESSION_TABLE_QUALITY_OF_TENNIS_COLUMN = "session_quality_of_tennis"
const val SESSION_TABLE_NUMBER_OF_STEPS_COLUMN = "session_number_of_steps"
const val SESSION_TABLE_NUMBER_OF_SHOTS_PLAYED_COLUMN = "session_number_of_shots_played"
const val SESSION_TABLE_VENUE_ID_COLUMN = "session_venue_id"